services:
  app-cep-temp-orch:
    build:
      context: .
      dockerfile: Dockerfile.Orchestrator
    container_name: cep-temp-orch
    restart: always
    ports:
      - 8080:8080 
    volumes:
      - ./orchestrator/config:/app/config
