services:
  app-cep-temp-orch:
    build:
      context: .
      dockerfile: Dockerfile.Orchestrator
    container_name: cep-temp-orch
    restart: always
    ports:
      - 8080:8080 
    volumes:
      - ./orchestrator/config:/app/config
  
  app-cep-input:
    build:
      context: .
      dockerfile: Dockerfile.Input
    container_name: cep-input
    restart: always
    ports:
      - 8090:8080
    volumes:
      - ./input/config:/app/config
      
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
